spring:
  application:
    name: checkout-service
  data:
    mongodb:
      database: checkout
      uuid-representation: standard

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8081