spring:
  application:
    name: shopping-service
  data:
    mongodb:
      database: shopping
      uuid-representation: standard

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8080

