spring:
  application:
    name: warehouse-service
  data:
    mongodb:
      database: warehouse
      uuid-representation: standard

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8083